export { default as echoQuery } from './echoQuery'
export { default as citiesQuery } from './citiesQuery'
export { default as continentsQuery } from './continentsQuery'
export { default as countriesQuery } from './countriesQuery'
export { default as propertyQuery } from './propertyQuery'